# Generated by Django 5.2.17 on 2026-09-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='اسم العميل')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='KeywordMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=180, unique=True, verbose_name='الكلمة المفتاحية')),
                ('monthly_volume', models.PositiveIntegerField(default=0, verbose_name='حجم البحث الشهري')),
                ('difficulty', models.PositiveSmallIntegerField(default=0, verbose_name='صعوبة المنافسة')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الترتيب الحالي')),
            ],
            options={
                'verbose_name': 'كلمة مفتاحية',
                'verbose_name_plural': 'الكلمات المفتاحية',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=30, verbose_name='الهاتف')),
                ('stage', models.CharField(choices=[('lead', 'عميل محتمل'), ('contacted', 'تم التواصل'), ('demo', 'عرض تجريبي'), ('customer', 'عميل')], default='lead', max_length=16, verbose_name='المرحلة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'فرصة بيع',
                'verbose_name_plural': 'فرص البيع',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='اسم الوكيل')),
                ('region', models.CharField(max_length=100, verbose_name='المنطقة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='العمولة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وكيل',
                'verbose_name_plural': 'الوكلاء',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنكليزية')),
                ('summary_ar', models.TextField(verbose_name='الوصف المختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('file', 'ملف')], max_length=10, verbose_name='النوع')),
                ('file_url', models.URLField(blank=True, verbose_name='رابط الملف')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.product', verbose_name='المنتج المرتبط')),
            ],
            options={
                'verbose_name': 'وسيط',
                'verbose_name_plural': 'الوسائط',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='مفتاح التفعيل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('trial', 'تجريبي'), ('expired', 'منتهي'), ('suspended', 'موقوف')], default='trial', max_length=16, verbose_name='الحالة')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='العميل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'ترخيص',
                'verbose_name_plural': 'التراخيص',
            },
        ),
    ]
